{{- if .Values.configMaps }}
{{- range $name, $configMap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "orders.labels" $ | nindent 4 }}
data:
  {{- toYaml $configMap.data | nindent 2 }}
{{- end }}
{{- end }}