{{- if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ include "micro-market-frontend.fullname" . }}
  labels:
    {{- include "micro-market-frontend.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "micro-market-frontend.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.peerAuthentication.mode }}
{{- end }}
