{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "catalog.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - {{ .Release.Namespace | quote }}
              {{- toYaml .Values.authorizationPolicy.allowedNamespaces | nindent 14 }}
{{- end }}
