{{- if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "catalog.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.peerAuthentication.mode }}
{{- end }}
